server:
  port: 8080
  address: 127.0.0.1

spring:
  application:
    name: my-finances-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/myfinances
    username: myfinances
    password: myfinances
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
